---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен иметь возможность удалять товары из корзины
  - Пользователь должен иметь возможность оформлять заказ и переходить на страницу оплаты
  - Пользователь должен иметь возможность продолжать выбирать товары в каталоге после добавления в корзину
  - Данные корзины должны сохраняться в сессии браузера, даже если страница будет обновлена
  - Система должна быть масштабируемой, чтобы можно было добавлять новые категории товаров в каталог
  - Сайт должен поддерживать мультиязычность
  - Сайт должен иметь возможность интеграции с платежными системами
  - Сайт должен иметь систему уведомлений
  - Сайт должен поддерживать возможность оставлять отзывы и оценки товарам
